export enum TarotMajorArcana {
  THE_DEVIL = 'the_devil',
  THE_FOOL = 'the_fool',
  DEATH = 'death',
  JUSTICE = 'justice',
  THE_WORLD = 'the_world',
  STRENGTH = 'strength',
  TEMPERANCE = 'temperance',
  THE_CHARIOT = 'the_chariot',
  THE_EMPEROR = 'the_emperor',
  THE_EMPRESS = 'the_empress',
  JUDGEMENT = 'judgement',
  THE_HANGED_MAN = 'the_hanged_man',
  THE_HERMIT = 'the_hermit',
  THE_HIEROPHANT = 'the_hierophant',
  THE_HIGH_PRIESTESS = 'the_high_priestess',
  THE_LOVERS = 'the_lovers',
  THE_MAGICIAN = 'the_magician',
  THE_MOON = 'the_moon',
  THE_STAR = 'the_star',
  THE_SUN = 'the_sun',
  THE_TOWER = 'the_tower',
  WHEEL_OF_FORTUNE = 'wheel_of_fortune',
}

export enum TarotMinorArcana {
  // --- SUIT OF WANDS (Bộ Gậy) ---
  ACE_OF_WANDS = 'ace_of_wands',
  TWO_OF_WANDS = 'two_of_wands',
  THREE_OF_WANDS = 'three_of_wands',
  FOUR_OF_WANDS = 'four_of_wands',
  FIVE_OF_WANDS = 'five_of_wands',
  SIX_OF_WANDS = 'six_of_wands',
  SEVEN_OF_WANDS = 'seven_of_wands',
  EIGHT_OF_WANDS = 'eight_of_wands',
  NINE_OF_WANDS = 'nine_of_wands',
  TEN_OF_WANDS = 'ten_of_wands',
  PAGE_OF_WANDS = 'page_of_wands',
  KNIGHT_OF_WANDS = 'knight_of_wands',
  QUEEN_OF_WANDS = 'queen_of_wands',
  KING_OF_WANDS = 'king_of_wands',

  // --- SUIT OF CUPS (Bộ Ly) ---
  ACE_OF_CUPS = 'ace_of_cups',
  TWO_OF_CUPS = 'two_of_cups',
  THREE_OF_CUPS = 'three_of_cups',
  FOUR_OF_CUPS = 'four_of_cups',
  FIVE_OF_CUPS = 'five_of_cups',
  SIX_OF_CUPS = 'six_of_cups',
  SEVEN_OF_CUPS = 'seven_of_cups',
  EIGHT_OF_CUPS = 'eight_of_cups',
  NINE_OF_CUPS = 'nine_of_cups',
  TEN_OF_CUPS = 'ten_of_cups',
  PAGE_OF_CUPS = 'page_of_cups',
  KNIGHT_OF_CUPS = 'knight_of_cups',
  QUEEN_OF_CUPS = 'queen_of_cups',
  KING_OF_CUPS = 'king_of_cups',

  // --- SUIT OF SWORDS (Bộ Kiếm) ---
  ACE_OF_SWORDS = 'ace_of_swords',
  TWO_OF_SWORDS = 'two_of_swords',
  THREE_OF_SWORDS = 'three_of_swords',
  FOUR_OF_SWORDS = 'four_of_swords',
  FIVE_OF_SWORDS = 'five_of_swords',
  SIX_OF_SWORDS = 'six_of_swords',
  SEVEN_OF_SWORDS = 'seven_of_swords',
  EIGHT_OF_SWORDS = 'eight_of_swords',
  NINE_OF_SWORDS = 'nine_of_swords',
  TEN_OF_SWORDS = 'ten_of_swords',
  PAGE_OF_SWORDS = 'page_of_swords',
  KNIGHT_OF_SWORDS = 'knight_of_swords',
  QUEEN_OF_SWORDS = 'queen_of_swords',
  KING_OF_SWORDS = 'king_of_swords',

  // --- SUIT OF PENTACLES (Bộ Tiền) ---
  ACE_OF_PENTACLES = 'ace_of_pentacles',
  TWO_OF_PENTACLES = 'two_of_pentacles',
  THREE_OF_PENTACLES = 'three_of_pentacles',
  FOUR_OF_PENTACLES = 'four_of_pentacles',
  FIVE_OF_PENTACLES = 'five_of_pentacles',
  SIX_OF_PENTACLES = 'six_of_pentacles',
  SEVEN_OF_PENTACLES = 'seven_of_pentacles',
  EIGHT_OF_PENTACLES = 'eight_of_pentacles',
  NINE_OF_PENTACLES = 'nine_of_pentacles',
  TEN_OF_PENTACLES = 'ten_of_pentacles',
  PAGE_OF_PENTACLES = 'page_of_pentacles',
  KNIGHT_OF_PENTACLES = 'knight_of_pentacles',
  QUEEN_OF_PENTACLES = 'queen_of_pentacles',
  KING_OF_PENTACLES = 'king_of_pentacles',
}

export enum TarotDeck {
  // --- MAJOR ARCANA ---
  THE_DEVIL = 'the_devil',
  THE_FOOL = 'the_fool',
  DEATH = 'death',
  JUSTICE = 'justice',
  THE_WORLD = 'the_world',
  STRENGTH = 'strength',
  TEMPERANCE = 'temperance',
  THE_CHARIOT = 'the_chariot',
  THE_EMPEROR = 'the_emperor',
  THE_EMPRESS = 'the_empress',
  JUDGEMENT = 'judgement',
  THE_HANGED_MAN = 'the_hanged_man',
  THE_HERMIT = 'the_hermit',
  THE_HIEROPHANT = 'the_hierophant',
  THE_HIGH_PRIESTESS = 'the_high_priestess',
  THE_LOVERS = 'the_lovers',
  THE_MAGICIAN = 'the_magician',
  THE_MOON = 'the_moon',
  THE_STAR = 'the_star',
  THE_SUN = 'the_sun',
  THE_TOWER = 'the_tower',
  WHEEL_OF_FORTUNE = 'wheel_of_fortune',

  // --- SUIT OF WANDS (Bộ Gậy) ---
  ACE_OF_WANDS = 'ace_of_wands',
  TWO_OF_WANDS = 'two_of_wands',
  THREE_OF_WANDS = 'three_of_wands',
  FOUR_OF_WANDS = 'four_of_wands',
  FIVE_OF_WANDS = 'five_of_wands',
  SIX_OF_WANDS = 'six_of_wands',
  SEVEN_OF_WANDS = 'seven_of_wands',
  EIGHT_OF_WANDS = 'eight_of_wands',
  NINE_OF_WANDS = 'nine_of_wands',
  TEN_OF_WANDS = 'ten_of_wands',
  PAGE_OF_WANDS = 'page_of_wands',
  KNIGHT_OF_WANDS = 'knight_of_wands',
  QUEEN_OF_WANDS = 'queen_of_wands',
  KING_OF_WANDS = 'king_of_wands',

  // --- SUIT OF CUPS (Bộ Ly) ---
  ACE_OF_CUPS = 'ace_of_cups',
  TWO_OF_CUPS = 'two_of_cups',
  THREE_OF_CUPS = 'three_of_cups',
  FOUR_OF_CUPS = 'four_of_cups',
  FIVE_OF_CUPS = 'five_of_cups',
  SIX_OF_CUPS = 'six_of_cups',
  SEVEN_OF_CUPS = 'seven_of_cups',
  EIGHT_OF_CUPS = 'eight_of_cups',
  NINE_OF_CUPS = 'nine_of_cups',
  TEN_OF_CUPS = 'ten_of_cups',
  PAGE_OF_CUPS = 'page_of_cups',
  KNIGHT_OF_CUPS = 'knight_of_cups',
  QUEEN_OF_CUPS = 'queen_of_cups',
  KING_OF_CUPS = 'king_of_cups',

  // --- SUIT OF SWORDS (Bộ Kiếm) ---
  ACE_OF_SWORDS = 'ace_of_swords',
  TWO_OF_SWORDS = 'two_of_swords',
  THREE_OF_SWORDS = 'three_of_swords',
  FOUR_OF_SWORDS = 'four_of_swords',
  FIVE_OF_SWORDS = 'five_of_swords',
  SIX_OF_SWORDS = 'six_of_swords',
  SEVEN_OF_SWORDS = 'seven_of_swords',
  EIGHT_OF_SWORDS = 'eight_of_swords',
  NINE_OF_SWORDS = 'nine_of_swords',
  TEN_OF_SWORDS = 'ten_of_swords',
  PAGE_OF_SWORDS = 'page_of_swords',
  KNIGHT_OF_SWORDS = 'knight_of_swords',
  QUEEN_OF_SWORDS = 'queen_of_swords',
  KING_OF_SWORDS = 'king_of_swords',

  // --- SUIT OF PENTACLES (Bộ Tiền) ---
  ACE_OF_PENTACLES = 'ace_of_pentacles',
  TWO_OF_PENTACLES = 'two_of_pentacles',
  THREE_OF_PENTACLES = 'three_of_pentacles',
  FOUR_OF_PENTACLES = 'four_of_pentacles',
  FIVE_OF_PENTACLES = 'five_of_pentacles',
  SIX_OF_PENTACLES = 'six_of_pentacles',
  SEVEN_OF_PENTACLES = 'seven_of_pentacles',
  EIGHT_OF_PENTACLES = 'eight_of_pentacles',
  NINE_OF_PENTACLES = 'nine_of_pentacles',
  TEN_OF_PENTACLES = 'ten_of_pentacles',
  PAGE_OF_PENTACLES = 'page_of_pentacles',
  KNIGHT_OF_PENTACLES = 'knight_of_pentacles',
  QUEEN_OF_PENTACLES = 'queen_of_pentacles',
  KING_OF_PENTACLES = 'king_of_pentacles',
}
